modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/RS-Insert-Export-Upgrade/issues/new/choose"
[[mods]]
modId="rsinsertexportupgrade"
version="${file.jarVersion}"
displayName="RS Insert Export Upgrade"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rs-insert-export-upgrade"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod adds a Insert and Export Upgrade."

[[dependencies.rsinsertexportupgrade]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rsinsertexportupgrade]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rsinsertexportupgrade]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
